# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFrameworkTools.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormFrameworkTools(object):
    def setupUi(self, FormFrameworkTools):
        FormFrameworkTools.setObjectName("FormFrameworkTools")
        FormFrameworkTools.resize(909, 628)
        self.gridLayout = QtWidgets.QGridLayout(FormFrameworkTools)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.codeEdit = Qsci.QsciScintilla(FormFrameworkTools)
        self.codeEdit.setToolTip("")
        self.codeEdit.setWhatsThis("")
        self.codeEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 0, 0, 5, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(FormFrameworkTools)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resultEdit = QtWidgets.QTextBrowser(self.groupBox_3)
        self.resultEdit.setObjectName("resultEdit")
        self.verticalLayout_2.addWidget(self.resultEdit)
        self.gridLayout.addWidget(self.groupBox_3, 4, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(FormFrameworkTools)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.argsEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.argsEdit.setObjectName("argsEdit")
        self.verticalLayout_3.addWidget(self.argsEdit)
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.runButton = QtWidgets.QPushButton(FormFrameworkTools)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 3, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(FormFrameworkTools)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBoxPort = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxPort.setMinimum(59595)
        self.spinBoxPort.setMaximum(65534)
        self.spinBoxPort.setObjectName("spinBoxPort")
        self.horizontalLayout.addWidget(self.spinBoxPort)
        self.buttonStartServer = QtWidgets.QPushButton(self.groupBox)
        self.buttonStartServer.setObjectName("buttonStartServer")
        self.horizontalLayout.addWidget(self.buttonStartServer)
        self.buttonResetCode = QtWidgets.QPushButton(self.groupBox)
        self.buttonResetCode.setObjectName("buttonResetCode")
        self.horizontalLayout.addWidget(self.buttonResetCode)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBoxPs = QtWidgets.QGroupBox(FormFrameworkTools)
        self.groupBoxPs.setObjectName("groupBoxPs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxPs)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEditAddress = QtWidgets.QLineEdit(self.groupBoxPs)
        self.lineEditAddress.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditAddress.setObjectName("lineEditAddress")
        self.gridLayout_2.addWidget(self.lineEditAddress, 0, 1, 1, 1)
        self.spinBoxPsPort = QtWidgets.QSpinBox(self.groupBoxPs)
        self.spinBoxPsPort.setMinimum(49494)
        self.spinBoxPsPort.setMaximum(65534)
        self.spinBoxPsPort.setObjectName("spinBoxPsPort")
        self.gridLayout_2.addWidget(self.spinBoxPsPort, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxPs)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.buttonConnect = QtWidgets.QPushButton(self.groupBoxPs)
        self.buttonConnect.setObjectName("buttonConnect")
        self.gridLayout_2.addWidget(self.buttonConnect, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxPs)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxPs)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(self.groupBoxPs)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout_2.addWidget(self.lineEditPassword, 1, 1, 1, 2)
        self.gridLayout.addWidget(self.groupBoxPs, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)

        self.retranslateUi(FormFrameworkTools)
        QtCore.QMetaObject.connectSlotsByName(FormFrameworkTools)

    def retranslateUi(self, FormFrameworkTools):
        _translate = QtCore.QCoreApplication.translate
        FormFrameworkTools.setWindowTitle(_translate("FormFrameworkTools", "PS连接测试工具"))
        self.groupBox_3.setTitle(_translate("FormFrameworkTools", "返回结果"))
        self.groupBox_2.setTitle(_translate("FormFrameworkTools", "设置运行参数"))
        self.runButton.setText(_translate("FormFrameworkTools", "运行"))
        self.groupBox.setTitle(_translate("FormFrameworkTools", "本地端口设置"))
        self.buttonStartServer.setText(_translate("FormFrameworkTools", "开启本地服务"))
        self.buttonResetCode.setText(_translate("FormFrameworkTools", "重置代码"))
        self.groupBoxPs.setTitle(_translate("FormFrameworkTools", "PS连接"))
        self.lineEditAddress.setText(_translate("FormFrameworkTools", "127.0.0.1"))
        self.label.setText(_translate("FormFrameworkTools", "地址："))
        self.buttonConnect.setText(_translate("FormFrameworkTools", "连接PS"))
        self.label_2.setText(_translate("FormFrameworkTools", "端口："))
        self.label_3.setText(_translate("FormFrameworkTools", "密码："))

from PyQt5 import Qsci

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormFrameworkTools = QtWidgets.QWidget()
    ui = Ui_FormFrameworkTools()
    ui.setupUi(FormFrameworkTools)
    FormFrameworkTools.show()
    sys.exit(app.exec_())

